import antfu from '@antfu/eslint-config';

export default antfu({
  rules: {
    'antfu/no-top-level-await': 'off',
    'perfectionist/sort-interfaces': [
      'warn',
      {
        type: 'natural',
        customGroups: {
          id: '[Ii]d$',
          index: '^index$',
          type: '^type$',
          ref: '^ref$',
          default: '^default$',
          required: '^required$',
          unique: '^unique$',
          accessToken: '^accessToken$',
          refreshToken: '^refreshToken$',
          createdAt: '^createdAt$',
          updatedAt: '^updatedAt$',
        },
        groups: [
          'id',
          'index',
          'type',
          'ref',
          'default',
          'required',
          'unique',
          'unknown',
          'accessToken',
          'refreshToken',
          'createdAt',
          'updatedAt',
        ],
        order: 'asc',
        partitionByComment: false,
      },
    ],
    'perfectionist/sort-object-types': [
      'warn',
      {
        type: 'natural',
        customGroups: {
          id: '[Ii]d$',
          index: '^index$',
          type: '^type$',
          ref: '^ref$',
          default: '^default$',
          required: '^required$',
          unique: '^unique$',
          accessToken: '^accessToken$',
          refreshToken: '^refreshToken$',
          createdAt: '^createdAt$',
          updatedAt: '^updatedAt$',
        },
        groups: [
          'id',
          'index',
          'type',
          'ref',
          'default',
          'required',
          'unique',
          'unknown',
          'accessToken',
          'refreshToken',
          'createdAt',
          'updatedAt',
        ],
        order: 'asc',
        partitionByComment: false,
      },
    ],
    'perfectionist/sort-objects': [
      'warn',
      {
        type: 'natural',
        customGroups: {
          id: '[Ii]d$',
          index: '^index$',
          type: '^type$',
          ref: '^ref$',
          default: '^default$',
          required: '^required$',
          unique: '^unique$',
          accessToken: '^accessToken$',
          refreshToken: '^refreshToken$',
          createdAt: '^createdAt$',
          updatedAt: '^updatedAt$',
        },
        groups: [
          'id',
          'index',
          'type',
          'ref',
          'default',
          'required',
          'unique',
          'unknown',
          'accessToken',
          'refreshToken',
          'createdAt',
          'updatedAt',
        ],
        order: 'asc',
        partitionByComment: false,
      },
    ],
    'perfectionist/sort-union-types': [
      'warn',
      {
        type: 'natural',
        groups: ['unknown', 'nullish'],
        order: 'asc',
      },
    ],
  },
  stylistic: {
    commaDangle: 'only-multiline',
    indent: 2,
    quotes: 'single',
    semi: true,
    severity: 'warn',
  },
});
