/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface File {
  filename: string;
  id: Generated<string>;
  mimetype: string;
  size: Int8;
  url: string;
}

export interface SuperAdmin {
  email: string;
  id: Generated<string>;
  imageFileId: string | null;
  name: string;
  password: string;
  phone: string;
}

export interface Todo {
  completed: Generated<boolean>;
  createdAt: Generated<Timestamp>;
  deletedAt: Timestamp | null;
  id: Generated<string>;
  isActive: Generated<boolean>;
  task: string;
  updatedAt: Generated<Timestamp>;
}

export interface DB {
  file: File;
  superAdmin: SuperAdmin;
  todo: Todo;
}
